# Generated by Django 4.2.7 on 2025-07-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='maintenance_activity',
            field=models.ForeignKey(blank=True, help_text='Associated maintenance activity (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='maintenance.maintenanceactivity'),
        ),
    ]
