# Generated by Django 4.2.7 on 2025-07-18 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_activitytypecategory_is_global'),
        ('events', '0002_calendarevent_maintenance_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='maintenance_activity',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='activity_type',
            field=models.ForeignKey(blank=True, help_text='Maintenance activity type (for maintenance events)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='maintenance.maintenanceactivitytype'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='actual_end',
            field=models.DateTimeField(blank=True, help_text='Actual end time (for maintenance events)', null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='actual_start',
            field=models.DateTimeField(blank=True, help_text='Actual start time (for maintenance events)', null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='estimated_duration_hours',
            field=models.PositiveIntegerField(default=2, help_text='Estimated duration in hours (for maintenance events)'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='frequency_days',
            field=models.PositiveIntegerField(default=365, help_text='Frequency in days (for maintenance events)'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Is this maintenance activity mandatory?'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='maintenance_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='scheduled', help_text='Maintenance status (for maintenance events)', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='next_due_date',
            field=models.DateField(blank=True, help_text='Next due date for recurring maintenance', null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='parts_required',
            field=models.TextField(blank=True, help_text='Parts required (for maintenance events)'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='safety_notes',
            field=models.TextField(blank=True, help_text='Safety considerations (for maintenance events)'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='tools_required',
            field=models.TextField(blank=True, help_text='Tools required (for maintenance events)'),
        ),
    ]
