# Generated by Django 4.2.7 on 2025-07-18 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0006_globalschedule_scheduleoverride_and_more"),
        ("events", "0003_remove_calendarevent_maintenance_activity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendarevent",
            name="activity_type",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="actual_end",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="actual_start",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="completion_notes",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="estimated_duration_hours",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="frequency_days",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="is_mandatory",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="is_recurring",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="maintenance_status",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="next_due_date",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="notification_sent",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="notify_assigned",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="parts_required",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="recurrence_pattern",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="safety_notes",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="tools_required",
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="maintenance_activity",
            field=models.ForeignKey(
                blank=True,
                help_text="Detailed maintenance activity (if this is a maintenance event)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calendar_events",
                to="maintenance.maintenanceactivity",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="description",
            field=models.TextField(blank=True, help_text="Brief event description"),
        ),
    ]
