# Generated by Django 4.2.7 on 2025-09-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_calendarevent_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(help_text="Type of event (format: 'activity_{id}' for maintenance activities)", max_length=50),
        ),
    ]
