version: '3.8'

services:
  web:
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/

  redis:
    restart: unless-stopped

  celery:
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped

  celery-beat:
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/var/www/static:ro
      - media_volume:/var/www/media:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates
    depends_on:
      - web
    restart: unless-stopped

  portainer:
    environment:
      - PORTAINER_HTTP_DISABLED=true  # Force HTTPS in production
    volumes:
      - ./ssl:/certs:ro  # SSL certificates for Portainer
    restart: unless-stopped

volumes:
  postgres_data_prod: