version: '3.8'

services:
  db:
    image: postgres:15
    container_name: maintenance_db_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME:-maintenance_dashboard_prod}
      POSTGRES_USER: ${DB_USER:-maintenance_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-SecureProdPassword2024!}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - maintenance_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-maintenance_user} -d ${DB_NAME:-maintenance_dashboard_prod}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  redis:
    image: redis:7-alpine
    container_name: maintenance_redis_prod
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - maintenance_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: maintenance_web_prod
    command: >
      sh -c "chmod +x /app/ensure-database.sh &&
             /app/ensure-database.sh &&
             python manage.py init_database --admin-username ${ADMIN_USERNAME:-admin} --admin-email ${ADMIN_EMAIL:-admin@maintenance.errorlog.app} --admin-password ${ADMIN_PASSWORD:-SecureAdminPassword2024!} &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 --max-requests 1000 --max-requests-jitter 100 maintenance_dashboard.wsgi:application"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "${WEB_PORT:-4405}:8000"
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY:-django-production-secret-key-change-this-immediately-2024}
      - DB_NAME=${DB_NAME:-maintenance_dashboard_prod}
      - DB_USER=${DB_USER:-maintenance_user}
      - DB_PASSWORD=${DB_PASSWORD:-SecureProdPassword2024!}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-maintenance.errorlog.app,10.0.0.28,localhost,127.0.0.1}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@maintenance.errorlog.app}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-SecureAdminPassword2024!}
      - DOMAIN=${DOMAIN:-errorlog.app}
      # Security Settings
      - SECURE_SSL_REDIRECT=True
      - SESSION_COOKIE_SECURE=True
      - CSRF_COOKIE_SECURE=True
      - SECURE_BROWSER_XSS_FILTER=True
      - SECURE_CONTENT_TYPE_NOSNIFF=True
      - SECURE_HSTS_SECONDS=31536000
      - SECURE_HSTS_INCLUDE_SUBDOMAINS=True
      - SECURE_HSTS_PRELOAD=True
      - CSRF_TRUSTED_ORIGINS=https://maintenance.errorlog.app,https://www.maintenance.errorlog.app
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - maintenance_network
      - proxy-network
    labels:
      # Traefik Configuration
      - "traefik.enable=true"
      - "traefik.http.routers.maintenance-web.rule=Host(`maintenance.errorlog.app`)"
      - "traefik.http.routers.maintenance-web.entrypoints=websecure"
      - "traefik.http.routers.maintenance-web.tls.certresolver=letsencrypt"
      - "traefik.http.routers.maintenance-web.tls.domains[0].main=maintenance.errorlog.app"
      - "traefik.http.routers.maintenance-web.tls.domains[0].sans=www.maintenance.errorlog.app"
      - "traefik.http.services.maintenance-web.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy-network"
      # Security Headers
      - "traefik.http.middlewares.maintenance-security.headers.sslredirect=true"
      - "traefik.http.middlewares.maintenance-security.headers.forcestsheader=X-Forwarded-Proto:https"
      - "traefik.http.middlewares.maintenance-security.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.maintenance-security.headers.customrequestheaders.X-Forwarded-Host=maintenance.errorlog.app"
      - "traefik.http.middlewares.maintenance-security.headers.customrequestheaders.X-Forwarded-Server=maintenance.errorlog.app"
      - "traefik.http.middlewares.maintenance-security.headers.customresponseheaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.maintenance-security.headers.customresponseheaders.X-Frame-Options=DENY"
      - "traefik.http.middlewares.maintenance-security.headers.customresponseheaders.X-XSS-Protection=1; mode=block"
      - "traefik.http.middlewares.maintenance-security.headers.customresponseheaders.Referrer-Policy=strict-origin-when-cross-origin"
      - "traefik.http.middlewares.maintenance-security.headers.customresponseheaders.Permissions-Policy=geolocation=(), microphone=(), camera=()"
      - "traefik.http.middlewares.maintenance-security.headers.customresponseheaders.Strict-Transport-Security=max-age=31536000; includeSubDomains; preload"
      - "traefik.http.middlewares.maintenance-security.headers.customresponseheaders.Content-Security-Policy=default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'; frame-ancestors 'none';"
      # Apply security middleware
      - "traefik.http.routers.maintenance-web.middlewares=maintenance-security"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/core/health/simple/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  celery:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: maintenance_celery_prod
    command: >
      sh -c "chmod +x /app/start_celery_prod.sh &&
             /app/start_celery_prod.sh"
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY:-django-production-secret-key-change-this-immediately-2024}
      - DB_NAME=${DB_NAME:-maintenance_dashboard_prod}
      - DB_USER=${DB_USER:-maintenance_user}
      - DB_PASSWORD=${DB_PASSWORD:-SecureProdPassword2024!}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - C_FORCE_ROOT=1
      # Celery Production Settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_WORKER_CONCURRENCY=2
      - CELERY_WORKER_MAX_TASKS_PER_CHILD=1000
      - CELERY_WORKER_PREFETCH_MULTIPLIER=1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - maintenance_network
    healthcheck:
      test: ["CMD-SHELL", "celery -A maintenance_dashboard inspect ping || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 90s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  celery-beat:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: maintenance_celery_beat_prod
    command: >
      sh -c "chmod +x /app/start_celery_beat_prod.sh &&
             /app/start_celery_beat_prod.sh"
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY:-django-production-secret-key-change-this-immediately-2024}
      - DB_NAME=${DB_NAME:-maintenance_dashboard_prod}
      - DB_USER=${DB_USER:-maintenance_user}
      - DB_PASSWORD=${DB_PASSWORD:-SecureProdPassword2024!}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      # Celery Beat Production Settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - maintenance_network
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'celery.*beat' || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 90s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  maintenance_network:
    driver: bridge
  proxy-network:
    external: true

volumes:
  postgres_data:
  static_volume:
  media_volume: