# WARNING: This file is for development environment only.
# Do NOT merge MaintDashboard/portainer-stack-dev.yml into the main branch.
# It is intended for use with the 'latest' or other development branches only.
#
# 🚀 PORTAINER DEPLOYMENT WITH VERSIONING:
# To enable git-based versioning in Portainer:
# 1. Set these environment variables in your Portainer stack:
#    GIT_COMMIT_COUNT=<number of commits>
#    GIT_COMMIT_HASH=<short commit hash>
#    GIT_BRANCH=<branch name>
#    GIT_COMMIT_DATE=<commit date>
# 2. Or use the portainer build script: ./scripts/portainer_build.sh
# 3. The version info will be available at /version/ and /version/html/

# Portainer Development Stack for Maintenance Dashboard

services:
  db-dev:
    image: postgres:15
    container_name: maintenance_db_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME:-maintenance_dashboard_dev}
      POSTGRES_USER: ${DB_USER:-maintenance_user_dev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-DevPassword2024!}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    networks:
      - maintenance_network_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-maintenance_user_dev} -d ${DB_NAME:-maintenance_dashboard_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  redis-dev:
    image: redis:7-alpine
    container_name: maintenance_redis_dev
    ports:
      - "6380:6379"
    networks:
      - maintenance_network_dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT_COUNT: ${GIT_COMMIT_COUNT:-0}
        GIT_COMMIT_HASH: ${GIT_COMMIT_HASH:-unknown}
        GIT_BRANCH: ${GIT_BRANCH:-unknown}
        GIT_COMMIT_DATE: ${GIT_COMMIT_DATE:-unknown}
    container_name: maintenance_web_dev
    entrypoint: ["./scripts/deployment/docker-entrypoint.sh"]
    command: ["python", "manage.py", "runserver", "--noreload", "0.0.0.0:8000"]
    volumes:
      - static_volume_dev:/app/staticfiles
      - media_volume_dev:/app/media
    ports:
      - "4406:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-development-secret-key-change-this-immediately-2024
      - DB_NAME=maintenance_dashboard_dev
      - DB_USER=maintenance_user_dev
      - DB_PASSWORD=DevPassword2024!
      - DB_HOST=db-dev
      - DB_PORT=5432
      - POSTGRES_USER=${DB_USER:-maintenance_user_dev}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-DevPassword2024!}
      - REDIS_URL=redis://redis-dev:6379/0
      - ALLOWED_HOSTS=dev.maintenance.errorlog.app,localhost,127.0.0.1,45.79.215.182
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@dev.maintenance.errorlog.app
      - ADMIN_PASSWORD=DevAdminPassword2024!
      - DOMAIN=dev.maintenance.errorlog.app
      # Development Security Settings
      - SECURE_SSL_REDIRECT=False
      - SESSION_COOKIE_SECURE=False
      - CSRF_COOKIE_SECURE=False
      - SECURE_BROWSER_XSS_FILTER=True
      - SECURE_CONTENT_TYPE_NOSNIFF=True
      - SECURE_HSTS_SECONDS=0
      - SECURE_HSTS_INCLUDE_SUBDOMAINS=False
      - SECURE_HSTS_PRELOAD=False
      - CSRF_TRUSTED_ORIGINS=http://dev.maintenance.errorlog.app,https://dev.maintenance.errorlog.app
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
      # Migration Conflict Resolution
      - MIGRATION_CONFLICT_RESOLUTION=True
      - AUTO_MERGE_MIGRATIONS=True
      - FORCE_MIGRATION_MERGE=False
      # Fresh Database Initialization
      - MAX_RETRIES=30
      - RETRY_DELAY=5
      - SKIP_DB_INIT=False
      - SKIP_COLLECTSTATIC=False
      # Branding System Configuration
      - BRANDING_AUTO_SETUP=True
      - BRANDING_SITE_NAME=Maintenance Dashboard (Dev)
      - BRANDING_SITE_TAGLINE=Development Environment
      - BRANDING_WINDOW_TITLE_PREFIX=Maintenance Dashboard
      - BRANDING_WINDOW_TITLE_SUFFIX=Dev
      - BRANDING_HEADER_BRAND_TEXT=Maintenance Dashboard (Dev)
      - BRANDING_PRIMARY_COLOR=#4299e1
      - BRANDING_SECONDARY_COLOR=#2d3748
      - BRANDING_ACCENT_COLOR=#3182ce
    depends_on:
      db-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    networks:
      - maintenance_network_dev
      - proxy-network
    labels:
      # Nginx Proxy Manager/Traefik Configuration for Development
      - "traefik.enable=true"
      - "traefik.http.routers.maintenance-web-dev.rule=Host(`dev.maintenance.errorlog.app`)"
      - "traefik.http.routers.maintenance-web-dev.entrypoints=websecure"
      - "traefik.http.routers.maintenance-web-dev.tls.certresolver=letsencrypt"
      - "traefik.http.routers.maintenance-web-dev.tls.domains[0].main=dev.maintenance.errorlog.app"
      - "traefik.http.services.maintenance-web-dev.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy-network"
      # Development Security Headers
      - "traefik.http.middlewares.maintenance-dev-security.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.maintenance-dev-security.headers.customrequestheaders.X-Forwarded-Host=dev.maintenance.errorlog.app"
      - "traefik.http.middlewares.maintenance-dev-security.headers.customrequestheaders.X-Forwarded-Server=dev.maintenance.errorlog.app"
      - "traefik.http.middlewares.maintenance-dev-security.headers.customresponseheaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.maintenance-dev-security.headers.customresponseheaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.middlewares.maintenance-dev-security.headers.customresponseheaders.X-XSS-Protection=1; mode=block"
      # Apply security middleware
      - "traefik.http.routers.maintenance-web-dev.middlewares=maintenance-dev-security"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/simple/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  celery-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT_COUNT: ${GIT_COMMIT_COUNT:-0}
        GIT_COMMIT_HASH: ${GIT_COMMIT_HASH:-unknown}
        GIT_BRANCH: ${GIT_BRANCH:-unknown}
        GIT_COMMIT_DATE: ${GIT_COMMIT_DATE:-unknown}
    container_name: maintenance_celery_dev
    entrypoint: ["./scripts/deployment/docker-entrypoint.sh"]
    command: ["celery"]
    environment:
      - DEBUG=True
      - SECRET_KEY=django-development-secret-key-change-this-immediately-2024
      - DB_NAME=maintenance_dashboard_dev
      - DB_USER=maintenance_user_dev
      - DB_PASSWORD=DevPassword2024!
      - DB_HOST=db-dev
      - DB_PORT=5432
      - POSTGRES_USER=${DB_USER:-maintenance_user_dev}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-DevPassword2024!}
      - REDIS_URL=redis://redis-dev:6379/0
      - C_FORCE_ROOT=1
      # Celery Development Settings
      - CELERY_BROKER_URL=redis://redis-dev:6379/0
      - CELERY_RESULT_BACKEND=redis://redis-dev:6379/0
      - CELERY_WORKER_CONCURRENCY=1
      - CELERY_WORKER_MAX_TASKS_PER_CHILD=500
      - CELERY_WORKER_PREFETCH_MULTIPLIER=1
      # Migration Conflict Resolution
      - MIGRATION_CONFLICT_RESOLUTION=True
      - MAX_RETRIES=30
      - RETRY_DELAY=5
      - SKIP_DB_INIT=False
    depends_on:
      db-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    networks:
      - maintenance_network_dev
    healthcheck:
      test: ["CMD-SHELL", "celery -A maintenance_dashboard inspect ping || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 90s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # celery-beat-dev removed - now runs in the same container as celery-dev using --beat flag

networks:
  maintenance_network_dev:
    driver: bridge
  proxy-network:
    external: true

volumes:
  postgres_data_dev:
  static_volume_dev:
  media_volume_dev: 