# Generated by Django 4.2.7 on 2025-07-09 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_location',
            field=models.ForeignKey(blank=True, help_text='Default location for new equipment and maintenance activities', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_site',
            field=models.ForeignKey(blank=True, help_text='Default site for dashboard filtering', limit_choices_to={'is_site': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_default_site', to='core.location'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('dark', 'Dark Theme'), ('light', 'Light Theme')], default='dark', help_text='User interface theme preference', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
