# Generated by Django 4.2.7 on 2025-07-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_performance_indexes'),
        ('core', '0004_add_customer_to_location'),
    ]

    operations = [
    ]
