# Generated by Django 4.2.7 on 2025-07-14 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_add_customer_to_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('manual', 'Operation Manual'), ('specification', 'Technical Specification'), ('wiring_diagram', 'Wiring Diagram'), ('schematic', 'Schematic Diagram'), ('datasheet', 'Data Sheet'), ('certification', 'Certification Document'), ('other', 'Other Document')], default='manual', help_text='Type of document', max_length=20)),
                ('title', models.CharField(help_text='Title of the document', max_length=200)),
                ('file', models.FileField(help_text='The document file (PDF, DOC, etc.)', upload_to='model_documents/')),
                ('description', models.TextField(blank=True, help_text='Description of the document')),
                ('version', models.CharField(blank=True, help_text="Document version (e.g., '1.0', 'Rev A')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this document is currently active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_model_documents', to=settings.AUTH_USER_MODEL)),
                ('equipment_category', models.ForeignKey(help_text='Equipment category this document applies to', on_delete=django.db.models.deletion.CASCADE, related_name='model_documents', to='core.equipmentcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Document',
                'verbose_name_plural': 'Model Documents',
                'ordering': ['equipment_category', 'document_type', 'title'],
                'unique_together': {('equipment_category', 'title', 'version')},
            },
        ),
    ]
