# Generated by Django 4.2.7 on 2025-07-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_playwrightdebuglog"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortainerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "portainer_url",
                    models.URLField(
                        blank=True,
                        help_text="Portainer instance URL (e.g., http://portainer:9000)",
                        max_length=500,
                    ),
                ),
                (
                    "portainer_user",
                    models.CharField(
                        blank=True,
                        help_text="Portainer username for API access",
                        max_length=100,
                    ),
                ),
                (
                    "portainer_password",
                    models.CharField(
                        blank=True,
                        help_text="Portainer password for API access",
                        max_length=255,
                    ),
                ),
                (
                    "stack_name",
                    models.CharField(
                        blank=True,
                        help_text="Docker stack name in Portainer",
                        max_length=100,
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Optional webhook secret for security",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Portainer Configuration",
                "verbose_name_plural": "Portainer Configuration",
            },
        ),
    ]
