# Generated by Django 4.2.7 on 2025-07-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_portainerconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="portainerconfig",
            name="image_tag",
            field=models.CharField(
                blank=True,
                default="latest",
                help_text="Docker image tag to use for updates (e.g., latest, main, v1.0)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="portainerconfig",
            name="portainer_url",
            field=models.URLField(
                blank=True,
                help_text="Portainer webhook URL (e.g., https://portainer:9000/api/stacks/webhooks/...)",
                max_length=500,
            ),
        ),
    ]
