# Generated by Django 4.2.7 on 2025-07-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_portainerconfig_image_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portainerconfig",
            name="polling_frequency",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled - Manual updates only"),
                    ("5min", "Every 5 minutes"),
                    ("15min", "Every 15 minutes"),
                    ("30min", "Every 30 minutes"),
                    ("1hour", "Every hour"),
                    ("6hours", "Every 6 hours"),
                    ("12hours", "Every 12 hours"),
                    ("daily", "Once per day"),
                ],
                default="disabled",
                help_text="How often to automatically check for and pull the newest version",
                max_length=20,
            ),
        ),
    ]
