# Generated by Django 4.2.7 on 2025-07-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_portainerconfig_polling_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="portainerconfig",
            name="last_check_date",
            field=models.DateTimeField(
                blank=True, help_text="Last time we checked for changes", null=True
            ),
        ),
        migrations.AddField(
            model_name="portainerconfig",
            name="last_commit_date",
            field=models.DateTimeField(
                blank=True, help_text="Last known git commit date", null=True
            ),
        ),
        migrations.AddField(
            model_name="portainerconfig",
            name="last_commit_hash",
            field=models.CharField(
                blank=True, help_text="Last known git commit hash", max_length=100
            ),
        ),
    ]
