# Generated by Django 4.2.7 on 2025-07-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_portainerconfig_last_check_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("America/Chicago", "Central Time (CT)"),
                    ("America/New_York", "Eastern Time (ET)"),
                    ("America/Denver", "Mountain Time (MT)"),
                    ("America/Los_Angeles", "Pacific Time (PT)"),
                    ("America/Anchorage", "Alaska Time (AKT)"),
                    ("Pacific/Honolulu", "Hawaii Time (HST)"),
                    ("UTC", "UTC"),
                    ("Europe/London", "London (GMT)"),
                    ("Europe/Paris", "Paris (CET)"),
                    ("Asia/Tokyo", "Tokyo (JST)"),
                    ("Australia/Sydney", "Sydney (AEST)"),
                ],
                default="America/Chicago",
                help_text="User's preferred timezone for displaying dates and times",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="theme_preference",
            field=models.CharField(
                choices=[("dark", "Dark Theme"), ("light", "Light Theme")],
                default="light",
                help_text="User interface theme preference",
                max_length=10,
            ),
        ),
    ]
