# Generated by Django 4.2.7 on 2025-09-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_modeldocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Logo', 'verbose_name_plural': 'Logos'},
        ),
        migrations.RemoveField(
            model_name='logo',
            name='favicon',
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='button_primary_color',
            field=models.CharField(default='#4299e1', help_text='Primary button background color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='button_primary_text_color',
            field=models.CharField(default='#ffffff', help_text='Primary button text color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='button_secondary_color',
            field=models.CharField(default='#718096', help_text='Secondary button background color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='button_secondary_text_color',
            field=models.CharField(default='#ffffff', help_text='Secondary button text color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='card_background_color',
            field=models.CharField(default='#2d3748', help_text='Card background color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='card_border_color',
            field=models.CharField(default='#4a5568', help_text='Card border color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='content_background_color',
            field=models.CharField(default='#1a2238', help_text='Main content background color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='content_text_color',
            field=models.CharField(default='#e2e8f0', help_text='Main content text color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='danger_color',
            field=models.CharField(default='#f56565', help_text='Danger color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='dropdown_background_color',
            field=models.CharField(default='#2d3748', help_text='Dropdown menu background color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='dropdown_background_opacity',
            field=models.DecimalField(decimal_places=2, default=0.95, help_text='Dropdown background opacity (0.00 to 1.00)', max_digits=3),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='dropdown_border_color',
            field=models.CharField(default='#4a5568', help_text='Dropdown menu border color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='dropdown_hover_background_color',
            field=models.CharField(default='#4a5568', help_text='Dropdown item hover background color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='dropdown_hover_text_color',
            field=models.CharField(default='#ffffff', help_text='Dropdown item hover text color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='dropdown_text_color',
            field=models.CharField(default='#e2e8f0', help_text='Dropdown menu text color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Website favicon (16x16, 32x32, or 48x48 recommended)', upload_to='favicons/'),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='form_background_color',
            field=models.CharField(default='#2d3748', help_text='Form background color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='form_border_color',
            field=models.CharField(default='#4a5568', help_text='Form border color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='form_text_color',
            field=models.CharField(default='#e2e8f0', help_text='Form text color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='header_background_color',
            field=models.CharField(default='#0f1419', help_text='Header background color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='header_border_color',
            field=models.CharField(default='#4a5568', help_text='Header border color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='header_text_color',
            field=models.CharField(default='#ffffff', help_text='Header text color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='info_color',
            field=models.CharField(default='#4299e1', help_text='Info color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='navigation_background_color',
            field=models.CharField(default='#2d3748', help_text='Navigation background color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='navigation_hover_color',
            field=models.CharField(default='#4299e1', help_text='Navigation hover color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='navigation_text_color',
            field=models.CharField(default='#e2e8f0', help_text='Navigation text color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='success_color',
            field=models.CharField(default='#48bb78', help_text='Success color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='warning_color',
            field=models.CharField(default='#ed8936', help_text='Warning color in hex format (#RRGGBB)', max_length=7),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='window_title_prefix',
            field=models.CharField(default='', help_text='Text to prepend to all page titles', max_length=100),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='window_title_suffix',
            field=models.CharField(default='', help_text='Text to append to all page titles', max_length=100),
        ),
        migrations.AlterField(
            model_name='csscustomization',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what this CSS customization does'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('dark', 'Dark Theme'), ('light', 'Light Theme')], default='light', help_text='User interface theme preference', max_length=10),
        ),
    ]
