# Generated by Django 4.2.7 on 2026-06-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_status_filters_to_dashboard_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='layout_height',
            field=models.FloatField(blank=True, help_text='Facility-map height (or canvas height for a site)', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='layout_width',
            field=models.FloatField(blank=True, help_text='Facility-map width (or canvas width for a site)', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='layout_x',
            field=models.FloatField(blank=True, help_text='Facility-map X (site canvas units)', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='layout_y',
            field=models.FloatField(blank=True, help_text='Facility-map Y (site canvas units)', null=True),
        ),
    ]
