# Generated by Django 5.2.4 on 2025-07-09 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique equipment name', max_length=200, unique=True)),
                ('manufacturer_serial', models.CharField(help_text='Manufacturer serial number', max_length=100, unique=True)),
                ('asset_tag', models.CharField(db_column='soluna_asset_tag', help_text='Internal asset tag', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('power_ratings', models.CharField(blank=True, max_length=200)),
                ('trip_setpoints', models.CharField(blank=True, max_length=200)),
                ('datasheet', models.FileField(blank=True, help_text='Equipment datasheet PDF', upload_to='equipment/datasheets/')),
                ('schematics', models.FileField(blank=True, help_text='Equipment schematics', upload_to='equipment/schematics/')),
                ('warranty_details', models.TextField(blank=True)),
                ('installed_upgrades', models.TextField(blank=True)),
                ('dga_due_date', models.DateField(blank=True, db_column='dga_due', help_text='DGA (Dissolved Gas Analysis) due date', null=True)),
                ('next_maintenance_date', models.DateField(blank=True, db_column='item_due_date', help_text='Next scheduled maintenance date', null=True)),
                ('commissioning_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(help_text='Equipment category', on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='core.equipmentcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='Equipment location', on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='core.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('replacement_date', models.DateField(blank=True, null=True)),
                ('next_replacement_date', models.DateField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='equipment.equipment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment Component',
                'verbose_name_plural': 'Equipment Components',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('manual', 'Operation Manual'), ('maintenance', 'Maintenance Manual'), ('drawing', 'Technical Drawing'), ('certificate', 'Certificate'), ('warranty', 'Warranty Document'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='equipment/documents/')),
                ('version', models.CharField(blank=True, max_length=20)),
                ('is_current', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='equipment.equipment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment Document',
                'verbose_name_plural': 'Equipment Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['name'], name='equipment_e_name_8baf3a_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['manufacturer_serial'], name='equipment_e_manufac_a794a5_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['asset_tag'], name='equipment_e_soluna__345a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['category', 'location'], name='equipment_e_categor_3f150e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentcomponent',
            unique_together={('equipment', 'name')},
        ),
    ]
