# Generated by Django 4.2.7 on 2025-07-14 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentdocument',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='equipmentdocument',
            name='version',
        ),
        migrations.AddField(
            model_name='equipmentdocument',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this document is currently active'),
        ),
        migrations.AlterField(
            model_name='equipmentdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentdocument',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the document'),
        ),
        migrations.AlterField(
            model_name='equipmentdocument',
            name='document_type',
            field=models.CharField(choices=[('photo', 'Equipment Photo'), ('note', 'Equipment Note'), ('specification', 'Equipment Specification'), ('wiring', 'Equipment Wiring'), ('other', 'Other Reference')], default='other', help_text='Type of reference document', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentdocument',
            name='equipment',
            field=models.ForeignKey(help_text='Equipment this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='equipmentdocument',
            name='file',
            field=models.FileField(help_text='The document file', upload_to='equipment/documents/'),
        ),
        migrations.AlterField(
            model_name='equipmentdocument',
            name='title',
            field=models.CharField(help_text='Title of the document', max_length=200),
        ),
    ]
