# Generated by Django 4.2.7 on 2025-07-18 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_userprofile_timezone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("equipment", "0002_remove_equipmentdocument_is_current_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentCategoryField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Field name (internal use)", max_length=100
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label for the field", max_length=200
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Long Text"),
                            ("number", "Number"),
                            ("decimal", "Decimal"),
                            ("date", "Date"),
                            ("datetime", "Date & Time"),
                            ("boolean", "Yes/No"),
                            ("select", "Dropdown"),
                            ("multiselect", "Multiple Choice"),
                            ("url", "URL"),
                            ("email", "Email"),
                            ("phone", "Phone Number"),
                        ],
                        default="text",
                        help_text="Type of field",
                        max_length=20,
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False, help_text="Is this field required?"
                    ),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True, help_text="Help text to display with the field"
                    ),
                ),
                (
                    "default_value",
                    models.TextField(
                        blank=True, help_text="Default value for the field"
                    ),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated choices for select fields",
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum value for number fields",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum value for number fields",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_length",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum length for text fields",
                        null=True,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for displaying fields"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this field active?"
                    ),
                ),
                (
                    "field_group",
                    models.CharField(
                        blank=True,
                        help_text="Group name for organizing fields (e.g., 'Electrical', 'Mechanical')",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Equipment category this field belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="core.equipmentcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Category Field",
                "verbose_name_plural": "Equipment Category Fields",
                "ordering": ["category", "sort_order", "name"],
                "unique_together": {("category", "name")},
            },
        ),
        migrations.CreateModel(
            name="EquipmentCustomValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.TextField(
                        blank=True, help_text="Value for the custom field"
                    ),
                ),
                (
                    "values_json",
                    models.TextField(
                        blank=True, help_text="JSON array for multiselect values"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        help_text="Equipment this value belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_values",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        help_text="Custom field this value belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="equipment.equipmentcategoryfield",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Custom Value",
                "verbose_name_plural": "Equipment Custom Values",
                "ordering": ["equipment", "field__sort_order"],
                "unique_together": {("equipment", "field")},
            },
        ),
    ]
