# Generated by Django 4.2.7 on 2025-09-03 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0004_equipmentcategoryconditionalfield'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='equipmentcategoryconditionalfield',
            new_name='equipment_e_source__76e455_idx',
            old_name='equipment_e_source__a0b8c8_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentcategoryconditionalfield',
            new_name='equipment_e_target__be1eff_idx',
            old_name='equipment_e_target__c0d9e0_idx',
        ),
        migrations.AlterField(
            model_name='equipmentcategoryconditionalfield',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentcategoryconditionalfield',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentdocument',
            name='document_type',
            field=models.CharField(choices=[('photo', 'Equipment Photo'), ('note', 'Equipment Note'), ('specification', 'Equipment Specification'), ('wiring', 'Equipment Wiring'), ('maintenance', 'Maintenance Report'), ('other', 'Other Reference')], default='other', help_text='Type of reference document', max_length=20),
        ),
    ]
