# Generated by Django 4.2.7 on 2026-06-04 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0022_reactivate_misdeactivated_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Brief title describing the issue', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Severity level of the issue', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', help_text='Current status of the issue', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the issue was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the issue was resolved')),
            ],
            options={
                'verbose_name': 'Equipment Issue',
                'verbose_name_plural': 'Equipment Issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Issue tag name (stored in lowercase)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the tag')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tag is active and available for use')),
            ],
            options={
                'verbose_name': 'Issue Tag',
                'verbose_name_plural': 'Issue Tags',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='equipmentconnection',
            new_name='equipment_e_upstrea_770617_idx',
            old_name='equipment_e_upstrea_9a2e5d_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentconnection',
            new_name='equipment_e_downstr_d2e2e8_idx',
            old_name='equipment_e_downstr_3f8a9c_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentconnection',
            new_name='equipment_e_connect_5a0e6d_idx',
            old_name='equipment_e_connect_7b4e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentfieldconfiguration',
            new_name='equipment_e_field_g_fd05f3_idx',
            old_name='equipment_e_field_g_7a8b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentfieldconfiguration',
            new_name='equipment_e_is_visi_46a751_idx',
            old_name='equipment_e_is_visi_8c9d3e_idx',
        ),
        migrations.AlterField(
            model_name='equipmentfieldconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentfieldconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuetag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuetag',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='equipment',
            field=models.ForeignKey(help_text='Equipment this issue is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='User who resolved the issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_equipment_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this issue', related_name='issues', to='equipment.issuetag'),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='issuetag',
            index=models.Index(fields=['name'], name='equipment_i_name_1b39c4_idx'),
        ),
        migrations.AddIndex(
            model_name='issuetag',
            index=models.Index(fields=['is_active'], name='equipment_i_is_acti_c8064e_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentissue',
            index=models.Index(fields=['equipment', '-created_at'], name='equipment_e_equipme_a55345_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentissue',
            index=models.Index(fields=['status'], name='equipment_e_status_40fce1_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentissue',
            index=models.Index(fields=['severity'], name='equipment_e_severit_56fda4_idx'),
        ),
    ]
