# Generated by Django 4.2.7 on 2025-07-13 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Report title', max_length=200)),
                ('report_type', models.CharField(choices=[('completion', 'Completion Report'), ('inspection', 'Inspection Report'), ('failure', 'Failure Report'), ('preventive', 'Preventive Maintenance Report'), ('corrective', 'Corrective Maintenance Report'), ('emergency', 'Emergency Maintenance Report'), ('other', 'Other')], default='completion', help_text='Type of maintenance report', max_length=20)),
                ('document', models.FileField(blank=True, help_text='Uploaded report document (PDF, DOCX, etc.)', null=True, upload_to='maintenance_reports/%Y/%m/')),
                ('content', models.TextField(blank=True, help_text='Report content (extracted from document or manually entered)')),
                ('summary', models.TextField(blank=True, help_text='Automatically generated summary of the report')),
                ('analyzed_data', models.JSONField(blank=True, default=dict, help_text='Structured data extracted from the report (issues, parts, measurements, etc.)')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this report has been processed for analysis')),
                ('processing_errors', models.TextField(blank=True, help_text='Any errors encountered during processing')),
                ('report_date', models.DateField(blank=True, help_text='Date the report was created (if different from upload date)', null=True)),
                ('technician_name', models.CharField(blank=True, help_text='Name of technician who performed the work', max_length=100)),
                ('work_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Hours spent on the maintenance work', max_digits=5, null=True)),
                ('activity', models.ForeignKey(help_text='Maintenance activity this report is for', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='maintenance.maintenanceactivity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Report',
                'verbose_name_plural': 'Maintenance Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity', 'report_type'], name='maintenance_activit_da135f_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='maintenance_uploade_1f0faa_idx'), models.Index(fields=['is_processed'], name='maintenance_is_proc_8bf725_idx')],
            },
        ),
    ]
