# Generated by Django 4.2.7 on 2025-07-13 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_general_category(apps, schema_editor):
    ActivityTypeCategory = apps.get_model('maintenance', 'ActivityTypeCategory')
    MaintenanceActivityType = apps.get_model('maintenance', 'MaintenanceActivityType')
    general_cat, _ = ActivityTypeCategory.objects.get_or_create(name='General', defaults={'description': 'General purpose category'})
    MaintenanceActivityType.objects.filter(category__isnull=True).update(category=general_cat)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_merge_20250713_0219'),
        ('maintenance', '0002_remove_category_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Category name (e.g., Preventive, Corrective, Inspection)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this activity category')),
                ('color', models.CharField(default='#007bff', help_text='Color for visual identification (hex code)', max_length=7)),
                ('icon', models.CharField(default='fas fa-wrench', help_text='FontAwesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Type Category',
                'verbose_name_plural': 'Activity Type Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='maintenanceactivitytype',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Maintenance Activity Type', 'verbose_name_plural': 'Maintenance Activity Types'},
        ),
        migrations.AddField(
            model_name='maintenanceactivitytype',
            name='applicable_equipment_categories',
            field=models.ManyToManyField(blank=True, help_text='Equipment categories this activity type applies to', related_name='applicable_activity_types', to='core.equipmentcategory'),
        ),
        migrations.AddField(
            model_name='maintenanceactivitytype',
            name='parts_required',
            field=models.TextField(blank=True, help_text='Parts required for this activity'),
        ),
        migrations.AddField(
            model_name='maintenanceactivitytype',
            name='safety_notes',
            field=models.TextField(blank=True, help_text='Safety considerations'),
        ),
        migrations.AddField(
            model_name='maintenanceactivitytype',
            name='tools_required',
            field=models.TextField(blank=True, help_text='Tools required for this activity'),
        ),
        migrations.CreateModel(
            name='ActivityTypeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Template name', max_length=100)),
                ('description', models.TextField(help_text='Template description')),
                ('estimated_duration_hours', models.PositiveIntegerField(default=1, help_text='Estimated duration in hours')),
                ('frequency_days', models.PositiveIntegerField(help_text='Frequency in days')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Is this activity mandatory?')),
                ('default_tools_required', models.TextField(blank=True, help_text='Default tools required')),
                ('default_parts_required', models.TextField(blank=True, help_text='Default parts required')),
                ('default_safety_notes', models.TextField(blank=True, help_text='Default safety considerations')),
                ('checklist_template', models.TextField(blank=True, help_text='Default checklist items (one per line)')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('category', models.ForeignKey(help_text='Activity type category', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='maintenance.activitytypecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('equipment_category', models.ForeignKey(help_text='Equipment category this template applies to', on_delete=django.db.models.deletion.CASCADE, related_name='activity_templates', to='core.equipmentcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Type Template',
                'verbose_name_plural': 'Activity Type Templates',
                'ordering': ['equipment_category', 'sort_order', 'name'],
                'unique_together': {('equipment_category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='maintenanceactivitytype',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Activity type category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_types', to='maintenance.activitytypecategory'),
        ),
        migrations.AddField(
            model_name='maintenanceactivitytype',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used to create this activity type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activity_types', to='maintenance.activitytypetemplate'),
        ),
        migrations.RunPython(set_general_category),
    ]
