# Generated by Django 4.2.7 on 2025-07-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_activitytypecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceactivitytype',
            name='category',
            field=models.ForeignKey(help_text='Activity type category', on_delete=django.db.models.deletion.CASCADE, related_name='activity_types', to='maintenance.activitytypecategory'),
        ),
    ]
