# Generated by Django 4.2.7 on 2025-07-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0004_make_maintenanceactivity_datetimes_aware"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitytypecategory",
            name="is_global",
            field=models.BooleanField(
                default=False,
                help_text="Global category for general-purpose activities",
            ),
        ),
    ]
