# Generated by Django 4.2.7 on 2025-07-18 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_playwrightdebuglog"),
        ("equipment", "0002_remove_equipmentdocument_is_current_and_more"),
        ("maintenance", "0005_activitytypecategory_is_global"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Global schedule name", max_length=200, unique=True
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frequency_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Custom frequency in days (for custom frequency type)",
                        null=True,
                    ),
                ),
                (
                    "auto_generate",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically generate maintenance activities",
                    ),
                ),
                (
                    "advance_notice_days",
                    models.PositiveIntegerField(
                        default=7, help_text="Days in advance to generate activities"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="Is this schedule mandatory for all equipment?",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allow_override",
                    models.BooleanField(
                        default=True,
                        help_text="Allow individual equipment to override this schedule",
                    ),
                ),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Default priority for activities generated from this schedule",
                        max_length=10,
                    ),
                ),
                (
                    "default_duration_hours",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Default duration in hours for activities generated from this schedule",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this global schedule"
                    ),
                ),
                (
                    "activity_type",
                    models.ForeignKey(
                        help_text="Type of maintenance activity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_schedules",
                        to="maintenance.maintenanceactivitytype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Global Schedule",
                "verbose_name_plural": "Global Schedules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this override active?"
                    ),
                ),
                (
                    "auto_generate",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically generate maintenance activities",
                    ),
                ),
                (
                    "advance_notice_days",
                    models.PositiveIntegerField(
                        default=7, help_text="Days in advance to generate activities"
                    ),
                ),
                (
                    "custom_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                            ("custom", "Custom"),
                        ],
                        help_text="Custom frequency for this equipment (overrides category/global)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "custom_frequency_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Custom frequency in days (for custom frequency type)",
                        null=True,
                    ),
                ),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Default priority for activities generated from this override",
                        max_length=10,
                    ),
                ),
                (
                    "default_duration_hours",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Default duration in hours for activities generated from this override",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes about this override"),
                ),
                (
                    "activity_type",
                    models.ForeignKey(
                        help_text="Type of maintenance activity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_overrides",
                        to="maintenance.maintenanceactivitytype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        help_text="Equipment this override applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_overrides",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Override",
                "verbose_name_plural": "Schedule Overrides",
                "ordering": ["equipment", "activity_type"],
                "unique_together": {("equipment", "activity_type")},
            },
        ),
        migrations.CreateModel(
            name="EquipmentCategorySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frequency_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Custom frequency in days (for custom frequency type)",
                        null=True,
                    ),
                ),
                (
                    "auto_generate",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically generate maintenance activities",
                    ),
                ),
                (
                    "advance_notice_days",
                    models.PositiveIntegerField(
                        default=7, help_text="Days in advance to generate activities"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="Is this schedule mandatory for all equipment in this category?",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allow_override",
                    models.BooleanField(
                        default=True,
                        help_text="Allow individual equipment to override this schedule",
                    ),
                ),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Default priority for activities generated from this schedule",
                        max_length=10,
                    ),
                ),
                (
                    "default_duration_hours",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Default duration in hours for activities generated from this schedule",
                    ),
                ),
                (
                    "activity_type",
                    models.ForeignKey(
                        help_text="Type of maintenance activity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_schedules",
                        to="maintenance.maintenanceactivitytype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment_category",
                    models.ForeignKey(
                        help_text="Equipment category this schedule applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_schedules",
                        to="core.equipmentcategory",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Category Schedule",
                "verbose_name_plural": "Equipment Category Schedules",
                "ordering": ["equipment_category", "activity_type"],
                "unique_together": {("equipment_category", "activity_type")},
            },
        ),
    ]
