# Generated by Django 4.2.7 on 2025-09-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_remove_maintenancereport_maintenance_activit_da135f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetimelineentry',
            name='entry_type',
            field=models.CharField(choices=[('created', 'Activity Created'), ('assigned', 'Activity Assigned'), ('started', 'Activity Started'), ('paused', 'Activity Paused'), ('resumed', 'Activity Resumed'), ('completed', 'Activity Completed'), ('cancelled', 'Activity Cancelled'), ('note', 'Note Added'), ('issue', 'Issue Reported'), ('resolution', 'Issue Resolved'), ('status_change', 'Status Changed'), ('unassigned', 'Activity Unassigned'), ('report_uploaded', 'Report Uploaded')], max_length=20),
        ),
    ]
