# Generated by Django 4.2.7 on 2026-01-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_alter_maintenancetimelineentry_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceactivity',
            name='deenergization_required',
            field=models.BooleanField(default=False, help_text='Whether de-energization is required for this maintenance activity'),
        ),
    ]
