# Generated by Django 4.2.7 on 2026-05-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_add_deenergization_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='frequency_overridden',
            field=models.BooleanField(default=False, help_text="Frequency was set manually for this schedule; do not overwrite it when the activity type's default frequency changes."),
        ),
    ]
